// export { default as DefaultPageView } from "./DefaultPageView"
// export { default as ContactsPageView } from "./ContactsPageView"
// export { default as ProductsPageView } from "./ProductsPageView"
// export { default as ProductPageView } from "./ProductPageView"
// export { default as AboutPageView } from "./AboutPageView"
export { default as FrontPageView } from "./FrontPageView"
