export const productsData = [
    {
        locale: "en",
        id: "223322",
        price: 33,
        name: "PC Monster",
        slug: "pc-monster",
        description: "### PC Monster description",
    },
    {
        locale: "lv",
        id: "223322",
        price: 33,
        name: "PC Monsteris",
        slug: "pc-monsteris",
        description: "### PC Monster apraksts",
    },
    {
        locale: "ru",
        id: "223322",
        price: 33,
        name: "ПК Монстр",
        slug: "пк-монстр",
        description: "### ПК Монстр описание",
    },
    {
        locale: "en",
        id: "131264",
        price: 77,
        name: "PC Monster 2",
        slug: "pc-monster 2",
        description: "### PC Monster descript 2ion",
    },
    {
        locale: "ru",
        id: "131264",
        price: 77,
        name: "ПК Монстр 2",
        slug: "пк-монстр 2",
        description: "### ПК Монстр описание 2",
    },
    {
        locale: "lv",
        id: "131264",
        price: 77,
        name: "PC Monsteris 2",
        slug: "pc-monsteris-2",
        description: "### PC Monster apraksts 2",
    },
]
